import React, { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowLeft, CheckCircle, Download, FileText } from 'lucide-react'
import Sidebar from '../components/layout/Sidebar'
import Card from '../components/ui/Card'
import Button from '../components/ui/Button'

export default function ModuleContentPage() {
  const { courseId, moduleId } = useParams()
  const navigate = useNavigate()
  const [completedLessons, setCompletedLessons] = useState([])

  // TODO: fetch from GET /api/courses/${courseId}/modules/${moduleId}/content
  const moduleData = {
    id: moduleId,
    title: moduleId === 'foundation' ? 'Foundation - Threat Detection Fundamentals' : `${moduleId} - Content`,
    description: 'Introduction to threat detection concepts and tools',
    lessons: [
      {
        id: '1',
        title: 'Understanding Threat Landscapes',
        content: `Threat landscapes encompass all potential cybersecurity threats that could target an organization's digital assets. This includes malware, phishing attacks, insider threats, and advanced persistent threats (APTs).

## Key Concepts:
- **Attack Vectors**: Methods attackers use to breach systems
- **Threat Actors**: Individuals or groups conducting attacks  
- **Vulnerabilities**: Weaknesses in systems that can be exploited

## Common Threat Types:
1. **Malware** - Malicious software designed to harm systems
2. **Phishing** - Social engineering attacks via email
3. **DDoS** - Distributed Denial of Service attacks
4. **Insider Threats** - Attacks from within the organization

\`\`\`bash
# Example: Basic network monitoring command
tcpdump -i eth0 -w capture.pcap
\`\`\`

**Best Practice**: Always assume your network is under surveillance and implement defense in depth.`
      },
      {
        id: '2', 
        title: 'Security Information and Event Management (SIEM)',
        content: `SIEM systems provide real-time analysis of security alerts generated by applications and network hardware.

## SIEM Components:
- **Log Collection**: Aggregating data from various sources
- **Correlation Engine**: Identifying patterns across events  
- **Alerting**: Notifying security teams of potential threats
- **Dashboards**: Visualizing security data

## Key Features:
- Real-time monitoring
- Threat intelligence integration
- Compliance reporting
- Incident response workflows

**Lab Exercise**: Configure a SIEM rule to detect multiple failed login attempts within 5 minutes.

\`\`\`python
# Example: Simple log analysis script
import re

def analyze_failed_logins(log_file):
    failed_attempts = {}
    with open(log_file, 'r') as f:
        for line in f:
            if 'Failed password' in line:
                ip = re.search(r'from (\S+)', line)
                if ip:
                    failed_attempts[ip.group(1)] = failed_attempts.get(ip.group(1), 0) + 1
    return failed_attempts
\`\`\``
      }
    ],
    resources: [
      { name: 'Threat Detection Checklist.pdf', type: 'pdf', size: '2.4 MB' },
      { name: 'SIEM Configuration Guide.docx', type: 'doc', size: '1.1 MB' },
      { name: 'Network Monitoring Scripts.zip', type: 'zip', size: '3.2 MB' }
    ]
  }

  const toggleLessonComplete = (lessonId) => {
    setCompletedLessons(prev => 
      prev.includes(lessonId) 
        ? prev.filter(id => id !== lessonId)
        : [...prev, lessonId]
    )
  }

  const downloadResource = (resource) => {
    // TODO: Implement actual download functionality
    console.log('Downloading:', resource.name)
  }

  const goBack = () => {
    navigate(`/courses/${courseId}/modules`)
  }

  return (
    <div className="flex min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900">
      <Sidebar />
      
      <main className="flex-1 p-6 overflow-auto">
        {/* Header with Back Button */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <Button
            variant="secondary"
            icon={<ArrowLeft className="w-4 h-4" />}
            onClick={goBack}
            className="mb-4"
          >
            Back to Modules
          </Button>

          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-3xl font-bold text-white mb-2">{moduleData.title}</h1>
              <p className="text-gray-400 text-lg">{moduleData.description}</p>
            </div>
            <div className="text-sm text-gray-300 bg-gray-800/50 px-3 py-2 rounded-lg">
              {completedLessons.length} of {moduleData.lessons.length} lessons completed
            </div>
          </div>
        </motion.div>

        <div className="flex flex-col lg:flex-row gap-8">
          {/* Main Content - 2/3 width */}
          <div className="flex-1 lg:w-2/3">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              {/* Lessons */}
              {moduleData.lessons.map((lesson, index) => (
                <Card 
                  key={lesson.id}
                  className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50"
                >
                  <div className="flex items-start gap-4">
                    <button
                      onClick={() => toggleLessonComplete(lesson.id)}
                      className={`flex-shrink-0 mt-1 ${
                        completedLessons.includes(lesson.id) 
                          ? 'text-green-400' 
                          : 'text-gray-400 hover:text-green-400'
                      }`}
                    >
                      <CheckCircle className="w-6 h-6" />
                    </button>
                    
                    <div className="flex-1">
                      <h3 className="text-xl font-semibold text-white mb-4">
                        {index + 1}. {lesson.title}
                      </h3>
                      
                      {/* Content with Markdown-like styling */}
                      <div className="prose prose-invert max-w-none">
                        {lesson.content.split('\n\n').map((paragraph, pIndex) => {
                          if (paragraph.startsWith('## ')) {
                            return (
                              <h4 key={pIndex} className="text-lg font-semibold text-cyan-400 mt-6 mb-3">
                                {paragraph.replace('## ', '')}
                              </h4>
                            )
                          } else if (paragraph.startsWith('```')) {
                            const codeMatch = paragraph.match(/```(\w+)\n([\s\S]*?)```/)
                            if (codeMatch) {
                              return (
                                <pre key={pIndex} className="bg-gray-900 rounded-lg p-4 overflow-x-auto my-4 border border-gray-700">
                                  <code className={`language-${codeMatch[1]} text-sm`}>{codeMatch[2]}</code>
                                </pre>
                              )
                            }
                          } else if (paragraph.startsWith('**') && paragraph.endsWith('**')) {
                            return (
                              <p key={pIndex} className="text-yellow-400 font-semibold my-3 text-lg">
                                {paragraph.replace(/\*\*/g, '')}
                              </p>
                            )
                          } else if (paragraph.startsWith('- **')) {
                            // List items with bold
                            return (
                              <ul key={pIndex} className="list-disc list-inside my-3 space-y-2">
                                {paragraph.split('\n').map((item, itemIndex) => (
                                  <li key={itemIndex} className="text-gray-300">
                                    <strong className="text-cyan-400">
                                      {item.replace('- **', '').replace('**', '')}
                                    </strong>
                                  </li>
                                ))}
                              </ul>
                            )
                          } else if (paragraph.startsWith('1. **')) {
                            // Numbered list with bold
                            return (
                              <ol key={pIndex} className="list-decimal list-inside my-3 space-y-2">
                                {paragraph.split('\n').map((item, itemIndex) => (
                                  <li key={itemIndex} className="text-gray-300">
                                    <strong className="text-cyan-400">
                                      {item.replace(/^\d+\.\s*\*\*/, '').replace(/\*\*/, '')}
                                    </strong>
                                  </li>
                                ))}
                              </ol>
                            )
                          } else {
                            return (
                              <p key={pIndex} className="text-gray-300 leading-relaxed mb-4">
                                {paragraph}
                              </p>
                            )
                          }
                        })}
                      </div>
                    </div>
                  </div>
                </Card>
              ))}

              {/* Resources */}
              <Card className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50">
                <h3 className="text-xl font-semibold text-white mb-4">Resources</h3>
                <div className="space-y-3">
                  {moduleData.resources.map((resource, index) => (
                    <div
                      key={index}
                      className="flex items-center justify-between p-4 bg-gray-700/30 rounded-lg hover:bg-gray-700/50 transition-colors"
                    >
                      <div className="flex items-center gap-3">
                        <FileText className="w-5 h-5 text-cyan-400" />
                        <div>
                          <div className="text-white font-medium">{resource.name}</div>
                          <div className="text-gray-400 text-sm">
                            {resource.type.toUpperCase()} • {resource.size}
                          </div>
                        </div>
                      </div>
                      <Button
                        variant="secondary"
                        size="sm"
                        icon={<Download className="w-4 h-4" />}
                        onClick={() => downloadResource(resource)}
                      >
                        Download
                      </Button>
                    </div>
                  ))}
                </div>
              </Card>
            </motion.div>
          </div>

          {/* Sidebar - 1/3 width */}
          <div className="lg:w-1/3 flex-shrink-0">
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              className="space-y-6"
            >
              {/* Progress Summary */}
              <Card className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50">
                <h3 className="text-lg font-semibold text-white mb-4">Lesson Progress</h3>
                <div className="space-y-4">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-white mb-1">
                      {Math.round((completedLessons.length / moduleData.lessons.length) * 100)}%
                    </div>
                    <div className="text-gray-400 text-sm">
                      {completedLessons.length} of {moduleData.lessons.length} lessons
                    </div>
                  </div>
                  
                  <div className="w-full bg-gray-700 rounded-full h-2">
                    <div 
                      className="bg-gradient-to-r from-cyan-500 to-blue-500 h-2 rounded-full transition-all duration-500"
                      style={{ width: `${(completedLessons.length / moduleData.lessons.length) * 100}%` }}
                    />
                  </div>
                </div>
              </Card>

              {/* Quick Navigation */}
              <Card className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50">
                <h3 className="text-lg font-semibold text-white mb-4">Continue Learning</h3>
                <div className="space-y-2">
                  <Button
                    variant="secondary"
                    className="w-full justify-start"
                    onClick={() => navigate(`/courses/${courseId}/modules/${moduleId}/video`)}
                  >
                    Watch Video Lesson
                  </Button>
                  <Button
                    variant="secondary"
                    className="w-full justify-start"
                    onClick={goBack}
                  >
                    Back to Module List
                  </Button>
                </div>
              </Card>
            </motion.div>
          </div>
        </div>
      </main>
    </div>
  )
}